### ISSUE TITLE
System for sprite boundaries does not function 

### ISSUE THREAD

**Issue by thecogdoctor** [thecogdoctor/ArenaGame#4]
- [Sprite.h](https://github.com/thecogdoctor/ArenaGame/blob/master/Sprite.h) 
- [Sprite.cpp](https://github.com/thecogdoctor/ArenaGame/blob/master/Sprite.cpp)
- [Player.h](https://github.com/thecogdoctor/ArenaGame/blob/master/Player.h)
- [Player.cpp](https://github.com/thecogdoctor/ArenaGame/blob/master/Player.cpp)
- [ArenaGame.ino](https://github.com/thecogdoctor/ArenaGame/blob/master/ArenaGame.ino)
- [ArenaGame.h](https://github.com/thecogdoctor/ArenaGame/blob/master/ArenaGame.h) 

TL:DR Player movement is not actually blocked by the system detailed below.

These are the files used in the system for sprite boundaries. 
Player tells the program whether the sprite has boundaries or to just let the player pass-through them here,
```cpp
//ArenaGame/ArenaGame.ino 
//Skipping a few lines for space's sake
#define SPRITEBOUNDARYMODE true

Sprite testprop = Sprite(SPRITEBOUNDARYMODE);
```
and here,
```cpp
//ArenaGame/ArenaGame.ino , later in the file 
void loop()
{
	if(displayWaitTime.ready() && running == false)
    {
    	Serial.println("Main Loop\n");
    	player.SpawnPlayerSprite('@');
    	testprop.SpawnStaticSprite();
    	player.SpriteBoundary(testprop.DetectChar(), TSX, TSY);
        running = true;
    }
    
    if(running)
    {
    	player.RenderPlayerSprite(onboard.Value());
    	testprop.RenderStaticSprite();
    	player.PlayerDebug(PLAYERPOSDEBUG);
    }
}
```
Here are the parts of Sprite.cpp that define this logic,
```cpp
//ArenaGame/Sprite.cpp 
Sprite::Sprite(bool useboundary): _useboundary(useboundary)
{
  //Trimmed out parts not relevant to this issue
  _useboundary = useboundary;
}

int Sprite::DetectChar()
{
  if(_useboundary)
  {
    switch(sprite)
    {
      case '@':
      Serial.println("This is the player character, choose another char!");
      return 0;
      break;
      
      case '#':
      Serial.println("THis char is used for is already in use. Please choose another char!");
      return 0;
      break;

      default:
      Serial.println("Character possible. Proceeding.");
      return 1;
      break;
    }
  } else {
    Serial.println("Boundaries for sprite not enabled");
    return 0;
  }
}
```
And in Player.cpp, 
```cpp
void Player::SpriteBoundary(int value, int x, int y)
{
  xbnd[0] = {x-1}; //Left side 
  xbnd[1] = {x};   //Left and right side
  xbnd[2] = {x+1};
  xbnd[3] = {x+2};
  xbnd[4] = {x+3};
  xbnd[5] = {x+4};
  xbnd[6] = {x+5};
  xbnd[7] = {x+6}; //Right side

  ybnd[0] = {y-1}; //Left
  ybnd[1] = {y};   //Left and right side
  ybnd[2] = {y+1};
  ybnd[3] = {y+2};
  ybnd[4] = {y+3};
  ybnd[5] = {y+4};
  ybnd[6] = {y+5};
  ybnd[7] = {y+6};
  ybnd[8] = {y+7};
  ybnd[9] = {y+8}; //Right side
  
  if(value == 1)
  { //Begin section for boundaries on left side of sprite
    bndrsenabled = true;
  }
}

void Player::MovePlayerSprite(int joystick)
{ 
  //Removed movement logic for the sake of making this less word to the user, the logic below is simply
  //restriction logic for the players movement. 
  if(bndrsenabled){
    //Begin section for boundaries on left side of sprite
    if(xpos >= xbnd[0] && ypos == (ybnd[0] || ybnd[1] || ybnd[2] || ybnd[3] || ybnd[4] || ybnd[5] || ybnd[6] || ybnd[7] || ybnd[8] || ybnd[9]))
    {
      xpos = xbnd[0] - 1; 
    }
    //End section for boundaries on left side of sprite

    //Right side section is near duplicate, except for xpos >= becomes xpos <= and xpos is set to equal 
    //xbnd[0] + 1;

    //Begin section for boundaries on top side of sprite. These boundaries 
    //don't cover left and right horizontal pixels, only the middle 5 pixels)
    if(xpos == (xbnd[1] || xbnd[2] || xbnd[3] || xbnd[4] || xbnd[5] || xbnd[6] || xbnd[7]) && ypos >= ybnd[9])
    {
      ypos = ybnd[0] - 1;
    } 
    //End section for boundaries on top side of sprite

    //Bottom section of sprite is nearly identical to top section, expect for "ypos >=" is "ypos <=" and 
    //"ypos = ybnd[0] - 1;" becomes "ypos = ybnd[0] + 1;"  
  }
```
System simply does not block the players movement through the sprite despite multiple configurations and approaches to the system. I will be adding more information as I work to debug this.  If a entire system re-write is needed so be it but my all that is needed at this point is to get the system functioning.

**Comment by Unchapped** [comment]
This may be where it starts to be necessary to re-structure some of your code:

I would look at adding a class called "Scene" or "Level" that keeps track of all of the sprites on a given stage of the game.

"Scene" could have a 2D array of Sprite pointers (or just an array of sprites, if you want to keep the memory management simple) in the dimension of the screen (assuming you're not scrolling around the world, otherwise, it would have a fixed size array the size of the whole level and could render some subset depending on where the screen is.

Then your Scene class could implement the following methods like so:
`
bool place_sprite(int x, int y, Sprite yolo){
	if isEmpty(x,y) {
		_sprites[x][y] = yolo; 
		return TRUE;
	} else return FALSE;
}
void remove_sprite(x,y) {
	_sprites[x][y] = NULL; //be careful here, null pointer exceptions don't segfault on arduino, it just makes your code go weird
}

isEmpty(int x, int y) {
	return _sprites[x][y] == NULL ;
}

bool move_sprite(int oldx, int oldy, int newx, int newy){
	if( isEmpty(newx, newy) {
		_sprites[newx][newy] = _sprites[oldx][oldy];
		_sprites[oldx][oldy] = NULL;
		return TRUE;
	} else return FALSE;
}

void render(AdafruitGFX *tft){ //render all the sprites in the scene at once
	tft.clear()
	for (int x = 0; x < WIDTH; x++){
		for (int y = 0; y < WIDTH; y++){
			_sprites[x][y].render(tft);
		}
	}
}
`
Implemented like that, you'd also add the scene pointer to your Sprite, so that your Sprite.move() function actually just calls the scene's move_sprite function. You'll also have to be very careful about memory management. This approach is fraught with peril, and very memory inefficient, but allows you to still implement your AI smarts and or special rendering subroutines (for example, an AnimatedSprite() class that overrides render to do something fancy).

**Comment by Unchapped** [comment]
A different, but safer approach would be for Scene to just be an array of 'chars' the size of the screen, and a render function to dump all the characters in the buffer to the screen.

Then all the smarts would be in your Sprite and/or monster classes, controlling its XY position, and it could still reference the isEmpty(X,Y) attribute of Level, but the sprite Render() function just draws itself to the scene's character buffer, and not the screen itself.

Given your level of coding, I recommend this second option as it's much safer, example code below.

`
class Scene {
	void render(adafruitGFX &tft); //implemented similar to above
	void isEmpty(x, y); //same as above
	public:
	char _sprites[WIDTH][HEIGHT];
}

///Updated Sprite Methods
//called once every time through the loop
Sprite::Update(Scene &target){
	//AI or Player-specific code goes here.
		//call move as needed
	self.render(target);
}

bool Sprite::move(int x, int y, Scene &target){
	if(target.isEmpty(x,y)) {
		target.sprites[_myX, _myY] = NULL;
		_myX = x;
		_myY = y;
		self.render(target);
		return TRUE;
		} else return FALSE;
}

Sprite::render(Scene &target){
	target.sprites[x][y] = _my_char;
}
`

**Comment by Unchapped** [comment]
The other benefit of this of course being that later you could eventually write a parser that reads in a text file from your SD card, creates all the needed sprites and a scene to go with them, and lays them out just as they look in the file, which would make 'level editing' much easier to do.

You could also make different types of scene subclasses for things like I.E. Menus and cutscenes. Though this would requrire a re-writing of the way your passing joystick commands in (they'd need to be looped through the scene class)

This allows a setup more like an [MVC structure](https://en.wikipedia.org/wiki/Model%E2%80%93view%E2%80%93controller).

Where a global list of sprites, as well as some sort of SaveGame struct for storing points etc. are your 'model', the 'Scene' class is your view, and your joystick parsing code/some stuff in the Scene is the 'controller'. It muddies the waters a bit, but the general pattern is there.
